I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1832, in script
    contered "Cadeado aberto"
Exception: Sayer 'contered' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1832, in script
    contered "Cadeado aberto"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'contered' is not defined.

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
Sombra 
Wed Sep 29 18:39:15 2021
